### ISSUE TITLE
Editor toolbar is broken when using this plugin with syntaxhighlighter3 plugin

### ISSUE THREAD

**Issue by sebastianstigler** [cosmocode/do#4]
When the plugin is used in additon to the syntaxhighlighter3 plugin (http://www.dokuwiki.org/plugin:syntaxhighlighter3 version 3.0.83) the toolbar in the editor gets broken (all quickbuttons are missing). When I deactivate the syntaxhighlighter3 or do plugin the toolbar is ok.

I'm using the dokuwiki release 2010-11-07a "Anteater" with the monobook template.

**Comment by micgro42** [comment]
I assume this is solved as well. Please reopen if it persists.
