### ISSUE TITLE
List of all tasks per user

### ISSUE THREAD

**Issue by innodan** [cosmocode/do#40]
Hello,

I want to create a dashboard which lists the tasks of the logged-in user. 

I use the following code:
`{{dolist>:?&status=undone&user=test&limit=10}}`

All tasks for the user "test" are shown, but if I log in as another user, there are listed test´s tasks, too. The goal is to list the user-specific tasks. Is it possible to use a replacement for the username or something else?

**Comment by vincentkersten** [comment]
Hello @innodan , I was also looking into this. 

Todolist (https://www.dokuwiki.org/plugin:todo) solves this with the  @@USER@@ macro replacement. I checked with the DO plugin but this did not work, so as a suggestion for you request I would +1 that solution. 

```
~~TODOLIST assigned:@@USER@@~~

~~TODOLIST assigned:@@MAIL@@~~ finds tasks assigned using someones email.
```
