### ISSUE TITLE
Tasks don't get removed on page deletion

### ISSUE THREAD

**Issue by sarnowski** [cosmocode/do#6]
- Create a page with tasks.
- (Mark the tasks as completed.)
- Edit the page, remove all content and save it (delete it)
- The tasks remain in the database

**Comment by fpoto** [comment]
The problem persists. The cure that I found is:

- locate the do.sqlite3 database
- install the sqlite3 package
cp <path>/do.sqlite3 ~/dobackup.sqlite3
sqlite3 <path>/do.sqlite3
select * from tasks;
- note the name of the page that has been deleted
select * from tasks where page='<page>';
- verify that the pages listed are in fact what you want to delete
delete from tasks where page='<page>';
select * from tasks;
- verify that the other pages are still there
.exit
