### ISSUE TITLE
Breaks with rc2020-06-01 "Hogfather"

### ISSUE THREAD

**Issue by karoshi42** [cosmocode/do#68]
If this plugin is active when upgrading, the whole wiki doesn't work afterwards and one has to manually remove or disable the plugin on the server.

The error is:

`[Tue Jun 02 23:11:41.889009 2020] [proxy_fcgi:error] [pid 25107] [client 127.0.0.1:8370] AH01071: Got error 'PHP message: PHP Warning:  require_once(/srv/dokuwiki/inc/JSON.php): failed to open stream: No such file or directory in /srv/dokuwiki/lib/plugins/do/action.php on line 15PHP message: PHP Fatal error:  require_once(): Failed opening required '/srv/dokuwiki/inc/JSON.php' (include_path='.:/usr/share/php') in /srv/dokuwiki/lib/plugins/do/action.php on line 15'`

which is correct, because [the latest update removed `inc/JSON.php`](https://github.com/splitbrain/dokuwiki/blob/master/data/deleted.files). I tried restoring only that file, but that didn't work, so for now the plugin has to be disabled.

**Comment by splitbrain** [comment]
fixed with #71
