### ISSUE TITLE
To mark the Checkbox is not possible with hogfather

### ISSUE THREAD

**Issue by donat1** [cosmocode/do#69]
It throws an error:

[php7:error] [pid 5213] [client 192.168.10.19:62142] PHP Fatal error:  Uncaught Error: Call to undefined method Doku_Handler::getCallWriter() in /var/www/dokuwiki/lib/plugins/do/syntax/do.php:96\nStack trace:\n#0 /var/www/dokuwiki/inc/parser/handler.php(240): syntax_plugin_do_do->handle('<do>', 1, 358, Object(Doku_Handler))\n#1 /var/www/dokuwiki/inc/Parsing/Lexer/Lexer.php(278): Doku_Handler->plugin('<do>', 1, 358, 'do_do')\n#2 /var/www/dokuwiki/inc/Parsing/Lexer/Lexer.php(212): dokuwiki\\Parsing\\Lexer\\Lexer->invokeHandler('<do>', 1, 358)\n#3 /var/www/dokuwiki/inc/Parsing/Lexer/Lexer.php(155): dokuwiki\\Parsing\\Lexer\\Lexer->dispatchTokens('', '<do>', 'plugin_do_do', 358, 358)\n#4 /var/www/dokuwiki/inc/Parsing/Parser.php(109): dokuwiki\\Parsing\\Lexer\\Lexer->parse('\\tAustrittsmeldu...')\n#5 /var/www/dokuwiki/inc/parserutils.php(216): dokuwiki\\Parsing\\Parser->parse('\\n===Checkliste ...')\n#6 /var/www/dokuwiki/inc/parserutils.php(181): p_get_instructions('===Checkliste A...')\n#7 /var/www/dokuwiki/inc/parserutils.php(501): p_cached_instructions('/var/www/dokuwi...', false, 'personal:2020:0...') in /var/www/dokuwiki/lib/plugins/do/syntax/do.php on line 96

**Comment by splitbrain** [comment]
fixed with #71
