### ISSUE TITLE
Some ./inc/JSON.php missing

### ISSUE THREAD

**Issue by ysfqar** [cosmocode/do#70]
I have just installed _Release rc2-2020-06-01 "Hogfather" RC2_. 
After installing _Do Plugin_ I get this error:
 
> Warning: require_once(./inc/JSON.php): failed to open stream: No such file or directory in ./lib/plugins/do/action.php on line 15

> Fatal error: require_once(): Failed opening required './inc/JSON.php' (include_path='.:/opt/remi/php73/root/usr/share/pear:/opt/remi/php73/root/usr/share/php:/usr/share/pear:/usr/share/php') in ./lib/plugins/do/action.php on line 15

Thanks for your help.

**Comment by splitbrain** [comment]
fixed with #71
